### ISSUE TITLE
Complete Mastodon Link Verification

### ISSUE THREAD

**Issue by iAnonymous3000** [nullNEU/nullify#23]
We need to finalize the Mastodon link verification for the website to establish our presence on the Fediverse and improve trust in our Mastodon account. The Mastodon account has been created and the link has been added to the website, but we need to complete the verification process.

## Objectives
- [ ] Implement rel="me" attribute on the existing Mastodon link for verification
- [ ] Add Mastodon verification meta tag to the website's <head> section
- [ ] Ensure Mastodon profile has a link back to our website
- [ ] Test and confirm Mastodon verification on both staging and production environments

## Technical Considerations
- The rel="me" attribute should be added to the existing Mastodon profile link in the HTML
- The verification meta tag should be added to the <head> section of the website
- Verify that the implementation doesn't interfere with existing meta tags or SEO optimizations
- Consider using Hugo's partial templates for consistent implementation across pages
- Be aware of potential caching issues that might delay verification

## Test verification:
   - Deploy changes to staging environment
   - Check if Mastodon recognizes the website link (may take a few minutes due to caching)
   - If verification fails, try clearing your browser cache or testing in an incognito window
   - Once verified on staging, deploy to production and repeat verification process

## Resources
- [Mastodon Verification Guide](https://docs.joinmastodon.org/user/profile/#verification)
- [Hugo Partial Templates](https://gohugo.io/templates/partials/)
- [Hugo Internal Templates for Social Media](https://gohugo.io/templates/internal/#social-media-metatags)

**Comment by iAnonymous3000** [comment]
The Mastodon verification appears to be properly configured:

1. Footer link has correct URL and rel="me" attribute:
```html
<a href="https://ioc.exchange/@null_NEU" target="_blank" rel="me">
```

2. Our Mastodon profile (https://ioc.exchange/@null_NEU) has the website link (nullneu.pages.dev)

Can we verify it works and close this issue? @Parthiv-M

**Comment by Parthiv-M** [comment]
Adding this here for context and closing, since everything seems good!

![image](https://github.com/user-attachments/assets/df3b9821-7f86-4dbc-8f43-9cb8efbc33a9)
