### ISSUE TITLE
Add a favicon for the site

### ISSUE THREAD

**Issue by Parthiv-M** [nullNEU/nullify#24]
## Design
Use the original null logo with a rounded border as the favicon

## Assets
- Possible logo file

  ![null_logo_file](https://github.com/user-attachments/assets/8ef80775-9ec8-4d3e-b44b-eb88a15fb3f8)

## Other resources
- [This converter](https://cloudconvert.com/svg-to-ico) might be helpful to generate an `ico` file
- [Favicons with Hugo](https://gohugo.io/getting-started/directory-structure/#static)

**Comment by MehekFatima** [comment]
Hi! I'd like to contribute to this issue

**Comment by Parthiv-M** [comment]
@MehekFatima let us know if you need any help
