### ISSUE TITLE
Add IVPN under VPNs

### ISSUE THREAD

**Issue by taivlam** [nullNEU/nullify#37]
It would be good to add [IVPN](https://www.ivpn.net/en/) to the list of suggested VPNs.

**Comment by iAnonymous3000** [comment]
While IVPN is a strong privacy-focused VPN provider with:
- No-logs policy and regular audits
- Open source applications across all platforms
- Transparent ownership and practices
- Strong ethical stance against misleading marketing
- Private DNS and AntiTracker features

Current recommendations pricing comparison:

Mullvad:
- Flat €5/month (~$5.50)
- No long-term plans
- Single tier with all features
- 5 simultaneous connections
- No student discount

ProtonVPN:
Monthly - $9.99/month
1-year - $4.99/month (billed $59.88, save $60)
2-year - $4.49/month (billed $107.76, save $132)
Free tier available with:
- 1 device
- No logs
- No ads
- Servers in 3 countries

Plus plan includes:
- 6500+ servers in 110+ countries
- 10 simultaneous devices
- Highest VPN speed
- All privacy features (streaming, P2P, Secure Core)

Student benefits:
- 50% off through Student Beans
- Includes full Proton suite (Mail, Drive, Calendar)

IVPN offers two tiers:
Standard ($6/month):
- 2 simultaneous devices
- Basic AntiTracker
- All protocols
Three-year plan: $140 ($3.89/month)

Pro ($10/month):
- 7 simultaneous devices
- Enhanced AntiTracker
- Multi-hop feature
- Port forwarding
Three-year plan: $220 ($6.11/month)
No student discount program

The pricing structure, especially with student discounts on already discounted long-term plans, plus the free tier and suite integration, makes ProtonVPN particularly student-friendly compared to both Mullvad (flat €5) and IVPN (starts at $6 for just 2 devices).

Still evaluating IVPN's potential inclusion, but the lack of student-specific programs and higher device limits make it a harder sell for our target audience. 

Thoughts on these pricing and feature comparisons for the student context?

**Comment by Parthiv-M** [comment]
Would greatly appreciate it if we can come to a decision whether or not to add IVPN to the list and update the website accordingly!

**Comment by taivlam** [comment]
@iAnonymous3000 I still think IVPN should be listed, though the reasons below are not directly about all the points you've listed.  The price

### Max number of devices
* Proton VPN: on the other hand, the student discount program only started in 2024 - so, as someone who started using VPNs since roughly 2020-2021, I don't really assume a VPN would usually offer student discounts.  Also, Proton is the only provider that offers any student discount.
    * Due to how recent this is, I can't really treat the existence of a student pricing plan as a standard customer offering.
    * Proton VPN has a max of 10 devices.
* Mullvad VPN: the max number of devices is 5.
    * Since the (nominal) price has the same for 10 years (at least, IIRC), I don't think there would be ever be a student discount from Mullvad.
* IVPN: the highest tier offers 7 devices, which is in the middle of the max number of devices from the other choices here.
    * Maybe IVPN could be open to this suggestion in the future, but that's for its customer service to consider.

### Payment methods
IVPN and Mullvad let customers pay with cash via an envelope, so I think there is value in still listing IVPN as an option.

I think Proton lets you pay via [cash](https://proton.me/support/pay-with-bitcoin), but you ideally should let Proton's customer service be aware of this in advance.  Also, the only cryptocurrency that Proton accepts is [Bitcoin](https://proton.me/support/pay-with-bitcoin), and there is no option for Monero or Zcash.  (I do remember a time, about 2 years ago or more, that you would have to contact Proton's customer service first to initiate cash payment, before sending the cash over mail.)

IVPN and Mullvad accept Monero and Bitcoin (among others, respectively), regarding cryptocurrencies.  Personally, despite the fact that I'm more technically inclined than the average person, I still find crytocurrencies intimidating to start and manage long-term.  So, if a target reader wants to use a private method to try out a VPN but isn't in a hurry to get immediate VPN service, then paying by cash should be considered.

### Non-profit pricing
IVPN offers "steep" discounted [pricing](https://www.ivpn.net/en/pricing-teams/) for non-profits on its highest tier plan.  The only other option that mentions anything similar is that you have to "manually" contact Proton's sales on its business plan [page](https://proton.me/business/plans).  Mullvad doesn't have this option (but then again, doesn't really need to from its unique pricing structure).

**Comment by iAnonymous3000** [comment]
Thanks for your contribution! 

IVPN is now included to the tools list. 

![image](https://github.com/user-attachments/assets/ff2db301-6921-4ff0-a57b-7dd345266a9b)

Link to IVPN: https://nullneu.pages.dev/tools/vpn/ivpn/
