### ISSUE TITLE
Switch from nullneu.pages.dev to custom domain (nullneu.org) with Security Hardening

### ISSUE THREAD

**Issue by iAnonymous3000** [nullNEU/nullify#39]
## Steps
1. Add CNAME record pointing to `nullneu.pages.dev`
2. Add custom domain in Cloudflare Pages settings
3. Verify SSL setup
4. Enable security settings in Cloudflare:
   - Force HTTPS
   - Enable HSTS
   - Set SSL/TLS encryption mode to Full (Strict)
   - Enable Browser Integrity Check
   - Enable WAF (Web Application Firewall)
5. Test website functionality

## Documentation
- [Custom Domain Setup Guide](https://developers.cloudflare.com/pages/platform/custom-domains/)
- [Cloudflare Security Guide](https://developers.cloudflare.com/security/)

**Comment by SirChronicle** [comment]
Hi! I'd like to take on this issue

**Comment by Parthiv-M** [comment]
Hi, since it's already been assigned to someone (in this case me), I'm afraid I cannot give it out to you. More so, this requires access to our Cloudfare, currently only with the E-Board. 

Feel free to take up any other task and be sure to check if it is already assigned to someone!

**Comment by SirChronicle** [comment]
oh okay, I'll make sure of that. Thanks!
