### ISSUE TITLE
Revamp Blog page

### ISSUE THREAD

**Issue by Parthiv-M** [nullNEU/nullify#5]
## Design

Design at: [Link to Figma](https://www.figma.com/design/ATWEej2IxPBlHcqV2zhO9l/nullNEU?node-id=0-1&t=WDbOXxbg19YujKHM-1)
Frame name: _Blog_

## Specifics

- Use same content as previous version
- Decide on better blog thumbnail image(s)

**Comment by nivgovind** [comment]
Assigning this to me(@nivgovind) @Parthiv-M
